spring.datasource.url : jdbc:mysql://localhost:3306/finalproject
spring.datasource.username : root
spring.datasource.password : testtest
spring.jpa.hibernate.ddl-auto : create
spring.datasource.driver-class-name=com :  mysql.jdbc.Driver


